print("hola mundo johana")
print(255)
print(255+60)
print("me encanta estudiar python")
print("Estudiar con python total es muy divertido")
print(600*50)
print(" \" hola mundo \" ")
print("hola\nmundo")
print("\thola mundo")
print(" \\ hola mundo")
