#input("¿Qué estas estudiando? ")
#input("¿en qué pais vives? ")
#input("Escribe tu nombre: ")
#input("Escribe tu apellido: ")
print("Actualmente estas estudiando: " + input("¿Qué estas estudiando? "))
print("Vives en: " + input("¿en qué pais vives?"))
print("Tu nombre completo es: "+ input("Escribe tu nombre: ") +"  "+ input("Escribe tu apellido: "))